services:
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - .:/app/media

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=${CELERY_URL}
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=${CELERY_URL}
    env_file:
      - .env
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
