# Generated by Django 5.1.3 on 2026-03-08 18:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2031, 3, 7))]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
