# Generated by Django 5.1.3 on 2026-03-08 18:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date(2031, 3, 7))]),
        ),
    ]
