# Generated by Django 5.1.3 on 2026-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('engine_type', models.CharField(max_length=20)),
            ],
        ),
    ]
