# Generated by Django 5.1.3 on 2026-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_status",
            field=models.CharField(
                choices=[("available", "Available"), ("rented", "Rented")],
                default="available",
                max_length=20,
            ),
        ),
    ]
