# Generated by Django 5.1.3 on 2026-04-17 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
