# Generated by Django 5.1.3 on 2026-04-22 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=150, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
