# Generated by Django 5.1.3 on 2026-06-01 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("hp", models.PositiveIntegerField(verbose_name="Horse Power")),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("gas", "Gas"),
                        ],
                        default="petrol",
                        max_length=50,
                    ),
                ),
                (
                    "number_plate",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Number Plate"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="VIN Number"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="cars/")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=150,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "car_status",
                    models.CharField(
                        choices=[("available", "Available"), ("rented", "Rented")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Car",
            },
        ),
    ]
