# Generated by Django 5.1.3 on 2026-06-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="rentals.rental",
                    ),
                ),
            ],
        ),
    ]
