name: API Status Badge Updater

on:
    schedule:
        - cron: "*/1 * * * *"
    workflow_dispatch:

jobs:
    update-badge:
        runs-on: ubuntu-latest
        steps:
            - name: Check API status and determine badge state
              id: check
              run: |
                  # Pobieramy sam kod odpowiedzi HTTP od Twojego API
                  HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" https://rent-car.ddns.net/api/docs/)

                  # Pobieramy obecną godzinę w strefie UTC (0-23)
                  HOUR_UTC=$(date -u +"%H")

                  if [ "$HTTP_STATUS" -eq 200 ]; then
                    echo "color=brightgreen" >> $GITHUB_OUTPUT
                    echo "message=Online" >> $GITHUB_OUTPUT
                  else
                    # Jeśli API nie odpowiada (np. timeout lub 502), sprawdzamy czy to okno serwisowe
                    # 18:00 UTC = 20:00 PL | 04:00 UTC = 06:00 PL
                    if [ "$HOUR_UTC" -ge 18 ] || [ "$HOUR_UTC" -lt 4 ]; then
                      echo "color=lightgrey" >> $GITHUB_OUTPUT
                      echo "message=Sleeping" >> $GITHUB_OUTPUT
                    else
                      # Jeśli jest środek dnia, a serwer nie odpowiada, to mamy realną awarię
                      echo "color=red" >> $GITHUB_OUTPUT
                      echo "message=Offline" >> $GITHUB_OUTPUT
                    fi
                  fi

            - name: Update Gist with new status
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GH_GIST_TOKEN }}
                  gistID: ${{ secrets.GIST_ID }}
                  filename: status.json
                  label: API Status
                  message: ${{ steps.check.outputs.message }}
                  color: ${{ steps.check.outputs.color }}
