name: Python Code Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flake8-check:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja środowiska Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Tu wpisujemy Twoją wersję Pythona

    - name: Instalacja Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Analiza kodu (Flake8)
      # Odpalamy linter w głównym katalogu (.). 
      # Ignorujemy błędy o długości linii > 119 znaków (standard dla Django)
      run: flake8 backend/ --count --max-line-length=119 --show-source --statistics